load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(name = "ids", hdrs = ["ids.h"], visibility = ["//visibility:public"])
cc_library(name = "clock", hdrs = ["clock.h"], visibility = ["//visibility:public"])
cc_library(
    name = "decimal",
    hdrs = ["decimal.h"],
    srcs = ["decimal.cc"],
    deps = ["@abseil-cpp//absl/status:status", "@abseil-cpp//absl/status:statusor", "@mpdecimal//:mpdecimal"],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "decimal_test",
    srcs = ["decimal_test.cc"],
    deps = [":decimal"],
)
