load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "config",
    hdrs = ["config.h"],
    srcs = ["config.cc"],
    deps = [
        "//hbot/base:decimal",
        "//hbot/base:ids",
        "//hbot/model:domain",
        "@abseil-cpp//absl/status:status",
        "@abseil-cpp//absl/status:statusor",
        "@yaml-cpp//:yaml-cpp",
    ],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "config_test",
    srcs = ["config_test.cc"],
    deps = [":config"],
)
