load("//:hquant_cc.bzl", "hquant_cc_library")

hquant_cc_library(
    name = "cli",
    srcs = ["cli.cc"],
    hdrs = ["cli.h"],
    deps = [
        "//hquant/src/application:config",
        "//hquant/src/application:quant_server",
        "//hquant/src/base:error",
        "@abseil-cpp//absl/status:status",
        "@abseil-cpp//absl/status:statusor",
    ],
    visibility = ["//visibility:public"],
)
