load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "cli",
    hdrs = ["cli.h"],
    srcs = ["cli.cc"],
    deps = [
        "//hbot/app/config:config",
        "//hbot/control:protocol",
        "@abseil-cpp//absl/status:status",
        "@abseil-cpp//absl/status:statusor",
    ],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "cli_test",
    srcs = ["cli_test.cc"],
    deps = [":cli"],
)
