load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "ids",
    hdrs = ["ids.h"],
    strip_include_prefix = "/hquant/src",
    include_prefix = "hquant",
    visibility = ["//hquant/src:__subpackages__"],
)

cc_library(
    name = "fixed",
    srcs = ["fixed.cc"],
    hdrs = ["fixed.h"],
    strip_include_prefix = "/hquant/src",
    include_prefix = "hquant",
    deps = [
        "@abseil-cpp//absl/status:status",
        "@abseil-cpp//absl/status:statusor",
    ],
    visibility = ["//hquant/src:__subpackages__"],
)

cc_library(
    name = "net",
    srcs = ["net.cc"],
    hdrs = ["net.h"],
    strip_include_prefix = "/hquant/src",
    include_prefix = "hquant",
    deps = [
        "@abseil-cpp//absl/status:status",
        "@abseil-cpp//absl/status:statusor",
        "@boost.asio//:boost.asio",
        "@boost.beast//:boost.beast",
        "@openssl//:ssl",
    ],
    visibility = ["//hquant/src:__subpackages__"],
)
