load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "private",
    hdrs = [
        "reconciliation.h",
        "user_data_stream.h",
    ],
    srcs = [
        "json_fields.h",
        "reconciliation.cc",
        "user_data_stream.cc",
    ],
    deps = [
        "//hbot/base:clock",
        "//hbot/base:decimal",
        "//hbot/base:ids",
        "//hbot/event:events",
        "//hbot/model:domain",
        "//hbot/net:api",
        "@abseil-cpp//absl/status:status",
        "@abseil-cpp//absl/status:statusor",
        "@boost.asio//:boost.asio",
        "@simdjson//:simdjson",
    ],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "private_test",
    srcs = ["private_test.cc"],
    deps = [
        ":private",
        "//hbot/connector:order_tracker",
        "@boost.asio//:boost.asio",
        "@googletest//:gtest_main",
    ],
)
