load("//:hquant_cc.bzl", "hquant_cc_library")

hquant_cc_library(
    name = "order_book",
    srcs = ["order_book.cc"],
    hdrs = ["order_book.h"],
    deps = [
        "//hquant/src/base:error",
        "//hquant/src/base:market",
        "@abseil-cpp//absl/container:btree",
    ],
    visibility = ["//visibility:public"],
)

hquant_cc_library(
    name = "market_data_stream",
    srcs = ["market_data_stream.cc"],
    hdrs = ["market_data_stream.h"],
    deps = [
        ":order_book",
        "//hquant/src/base:error",
        "//hquant/src/base:market",
        "//hquant/src/base:net",
        "//hquant/src/base:types",
        "@abseil-cpp//absl/status:status",
        "@abseil-cpp//absl/status:statusor",
        "@boost.asio//:boost.asio",
        "@simdjson//:simdjson",
    ],
    visibility = ["//hquant/src/application:__pkg__", "//hquant/test:__pkg__"],
)

hquant_cc_library(
    name = "replay_feed",
    srcs = ["replay_feed.cc"],
    hdrs = ["replay_feed.h"],
    deps = [
        "//hquant/src/base:error",
        "//hquant/src/base:market",
        "//hquant/src/base:types",
        "@abseil-cpp//absl/status:status",
        "@abseil-cpp//absl/status:statusor",
        "@simdjson//:simdjson",
    ],
    visibility = ["//examples:__pkg__", "//hquant/src/application:__pkg__", "//hquant/test:__pkg__"],
)
