load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "api", hdrs = ["api.h"],
    deps = ["//hbot/base:clock", "//hbot/market_data:book_view", "//hbot/model:domain"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "simple_pmm",
    srcs = ["simple_pmm.cc"],
    hdrs = ["simple_pmm.h"],
    deps = [":api", "//hbot/base:decimal", "//hbot/model:domain"],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "simple_pmm_test",
    srcs = ["simple_pmm_test.cc"],
    data = ["//tests/fixtures:simple_pmm_data"],
    deps = [":simple_pmm", "//tests/fixtures:all_fixtures", "@googletest//:gtest_main", "@simdjson//:simdjson"],
)
